"""Initial schema

Revision ID: 6f1bcc946e48
Revises: None
Create Date: 2026-07-14 14:19:47.999102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f1bcc946e48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('tenure', sa.Integer(), nullable=True),
    sa.Column('satisfaction_score', sa.Integer(), nullable=True),
    sa.Column('num_orders', sa.Integer(), nullable=True),
    sa.Column('total_spending', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_purchase_date', sa.Date(), nullable=True),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('warehouse_to_home', sa.Integer(), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('num_addresses', sa.Integer(), nullable=True),
    sa.Column('num_devices_registered', sa.Integer(), nullable=True),
    sa.Column('days_since_last_order', sa.Integer(), nullable=True),
    sa.Column('cashback_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('complain', sa.Integer(), nullable=True),
    sa.Column('churn', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_product_category'), 'customers', ['product_category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('result_value', sa.String(length=255), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_created_at'), 'predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_predictions_customer_id'), 'predictions', ['customer_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('recommendation_text', sa.Text(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_created_at'), 'recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommendations_customer_id'), 'recommendations', ['customer_id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_date'), 'sales', ['date'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_sales_date'), table_name='sales')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_recommendations_customer_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_created_at'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_predictions_customer_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_created_at'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_customers_product_category'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
